### PR TITLE
Add simple loan calculator app

### PR DESCRIPTION
**Pull request by techno-knight**
Tech stack  HTML, CSS and JavaScript.

### CODE REVIEW

**Comment by techno-knight** [comment]
@prankshaw  Any suggestion on how to pass checks ?

**Comment by prankshaw** [comment]
Don't worry about the check, It's a greetings.yml check fail. It's in Beta probably some issue.

**Comment by prankshaw** [comment]
Please add at least 1 screenshot of your project, inside the screenshot folder in your project. Then I will merge it.

**Comment by prankshaw** [comment]
@prime417

**Comment by techno-knight** [comment]
@prankshaw Can you accept PR?

**Pull request closed without merging**
